[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Do not force NODE_ENV here; Netlify needs devDependencies (e.g., TypeScript) during build